[tool.ruff]
# Base rules and formatting
line-length = 88
select = ["E", "F", "I", "W", "N", "UP", "PL", "RUF"]
ignore = [
    "E501",  # Line too long
    "W505",  # Doc line too long
]

# Enable autofix behavior
fix = true
unfixable = ["F401"]  # Allow fixing unused imports

# Format configuration
[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"